export const CLEAR_GLOBAL_STORE = 'CLEAR_GLOBAL_STORE';

export const LOGIN_USER = "LOGIN_USER";
export const LOGIN_USER_SUCCESS = "LOGIN_USER_SUCCESS";
export const LOGIN_USER_FAILURE = "LOGIN_USER_FAILURE";

export const FETCH_COFFEE_DETAILS = "FETCH_COFFEE_DETAILS";
export const FETCH_COFFEE_DETAILS_SUCCESS = "FETCH_COFFEE_DETAILS_SUCCESS";
export const FETCH_COFFEE_DETAILS_FAILURE = "FETCH_COFFEE_DETAILS_FAILURE";